name: checks
on:
  - pull_request
  - push
jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest
    runs-on: '${{ matrix.os }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Wrapper Validation
        uses: gradle/actions/wrapper-validation@v3
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: adopt
      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew build
